name: passmaker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  path_provider: ^2.1.5
  meta: ^1.15.0
  equatable: ^2.0.7
  hydrated_bloc: ^9.1.5
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  flutter_native_splash: ^2.4.3
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.2.0+3
  get: ^4.6.6
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
